import { chromium } from '@playwright/test';
import { preview } from 'vite';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
const security=JSON.parse(await readFile('config/security.local.json','utf8'));
const personal=JSON.parse(await readFile('public/data/brief.json','utf8'));
const server=process.env.PRIVACY_TEST_URL?null:await preview({preview:{host:'127.0.0.1',port:4174,strictPort:true}});
const base=process.env.PRIVACY_TEST_URL||'http://127.0.0.1:4174/';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${base}?privacy=${Date.now()}`);
 await page.locator('#unlock-password').waitFor();
 assert.equal(await page.locator('.page').isVisible(),false);
 assert.equal(await page.locator('#agenda-content').innerText(),'Your plans are on their way…');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'test-results/locked-mobile.png'});
 await page.locator('#unlock-password').fill('wrong-password-for-verification');await page.locator('#unlock-form button').click();
 await page.waitForFunction(()=>document.querySelector('#unlock-status').textContent.includes('Couldn’t unlock'));
 assert.equal(await page.locator('.page').isVisible(),false);
 await page.locator('#unlock-password').fill(security.password);await page.locator('#unlock-form button').click();
 await page.locator('.page').waitFor({state:'visible'});
 assert.equal(await page.locator('#finance-content .finance-item').count(),personal.finance.length);
 assert.equal(await page.locator('#deliveries-content .delivery-item').count(),personal.deliveries.shipments.length);
 assert.equal(await page.locator('#unlock-password').inputValue(),'');
 const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));
 assert.equal(storage.includes(security.password),false);
 if(personal.deliveries.shipments[0]?.id)assert.equal(storage.includes(personal.deliveries.shipments[0].id),false);
 await page.locator('#lock-button').click();assert.equal(await page.locator('.page').isVisible(),false);
 assert.equal(await page.locator('#deliveries-content').textContent(),'');
 await page.reload();await page.locator('#unlock-password').waitFor();assert.equal(await page.locator('.page').isVisible(),false);
 const response=await page.request.get(new URL('data/brief.enc.json',base).href+'?verify='+Date.now());assert.equal(response.status(),200);
 const encrypted=await response.json();assert.equal(encrypted.cipher,'AES-256-GCM');assert.equal(encrypted.calendar,undefined);assert.equal(encrypted.deliveries,undefined);
 const old=await page.request.get(new URL('data/brief.json',base).href+'?verify='+Date.now());
 const oldBody=await old.text();assert.equal(oldBody.includes('"calendar":'),false);assert.equal(oldBody.includes(security.password),false);
 if(!server)assert.equal(old.status(),404);
 assert.deepEqual(errors,[]);
 console.log('Verified lock screen, wrong-password rejection, correct-password decryption, clear-on-lock, reload locking, no stored password/personal data, encrypted payload, and no public plaintext edition.');
}finally{await browser.close();await new Promise(resolve=>server?server.httpServer.close(resolve):resolve());}
